In [244]:
# 获取数据

In [483]:
from bs4 import BeautifulSoup
import urllib.parse
import pandas as pd
from pymysql.converters import escape_string

In [484]:
url = 'http://www.shfe.com.cn/products/cu/'
head = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 Edg/89.0.774.63"}
data = pd.read_html(url)

In [485]:
columns = data[0].values[0]
df = data[1].copy()
df.columns = columns
df['name'] = escape_string('铜')
df['name']=df['name'].str.encode(encoding = 'raw_unicode_escape')#.name.decode("utf8")
df['exchange'] = 'SHFE'
# df['name']= df['name'].astype(str)
df

      合约代码       上市日       到期日     开始交割日     最后交割日  挂牌基准价        name exchange
0   cu2106  20200616  20210615  20210616  20210618  46520  b'\\u94dc'     SHFE
1   cu2107  20200716  20210715  20210716  20210720  51950  b'\\u94dc'     SHFE
2   cu2108  20200818  20210816  20210817  20210819  50960  b'\\u94dc'     SHFE
3   cu2109  20200916  20210915  20210916  20210922  52470  b'\\u94dc'     SHFE
4   cu2110  20201016  20211015  20211018  20211020  51690  b'\\u94dc'     SHFE
5   cu2111  20201117  20211115  20211116  20211118  53630  b'\\u94dc'     SHFE
6   cu2112  20201216  20211215  20211216  20211220  57910  b'\\u94dc'     SHFE
7   cu2201  20210118  20220117  20220118  20220120  59810  b'\\u94dc'     SHFE
8   cu2202  20210208  20220215  20220216  20220218  58150  b'\\u94dc'     SHFE
9   cu2203  20210316  20220315  20220316  20220318  67860  b'\\u94dc'     SHFE
10  cu2204  20210416  20220415  20220418  20220420  67560  b'\\u94dc'     SHFE
11  cu2205  20210518  20220516  20220517  20220519  75650  b'\\u94dc'     SHFE

In [486]:
import pymysql
import pandas as pd  
from sqlalchemy import create_engine 
yconnect = create_engine('mysql+pymysql://root:0000@localhost:3306/futures_c?charset=utf8mb4')  #
pd.io.sql.to_sql(df,'shfe_l', yconnect, schema='futures_c' , index = False, index_label=None,if_exists='replace')

In [491]:
import pymysql
import pandas as pd
 
conn = pymysql.connect(host = "localhost",port=3306,user='root',passwd='0000',db='futures_c',charset="utf8")
sql_query = 'SELECT * FROM shfe_l'
df1 = pd.read_sql(sql_query, con=conn)
 
conn.close()  #使用完后记得关掉
df1

      合约代码       上市日       到期日     开始交割日     最后交割日  挂牌基准价    name exchange
0   cu2106  20200616  20210615  20210616  20210618  46520  \u94dc     SHFE
1   cu2107  20200716  20210715  20210716  20210720  51950  \u94dc     SHFE
2   cu2108  20200818  20210816  20210817  20210819  50960  \u94dc     SHFE
3   cu2109  20200916  20210915  20210916  20210922  52470  \u94dc     SHFE
4   cu2110  20201016  20211015  20211018  20211020  51690  \u94dc     SHFE
5   cu2111  20201117  20211115  20211116  20211118  53630  \u94dc     SHFE
6   cu2112  20201216  20211215  20211216  20211220  57910  \u94dc     SHFE
7   cu2201  20210118  20220117  20220118  20220120  59810  \u94dc     SHFE
8   cu2202  20210208  20220215  20220216  20220218  58150  \u94dc     SHFE
9   cu2203  20210316  20220315  20220316  20220318  67860  \u94dc     SHFE
10  cu2204  20210416  20220415  20220418  20220420  67560  \u94dc     SHFE
11  cu2205  20210518  20220516  20220517  20220519  75650  \u94dc     SHFE

In [482]:
eval(repr(df1.name[0]).replace('\\\\', '\\'))

NameError: name 'nan' is not defined

In [469]:
type(df1.name[0])

str

In [492]:
df1.name = df1.name.apply(lambda x:eval(repr(x).replace('\\\\', '\\')))
df1

      合约代码       上市日       到期日     开始交割日     最后交割日  挂牌基准价 name exchange
0   cu2106  20200616  20210615  20210616  20210618  46520    铜     SHFE
1   cu2107  20200716  20210715  20210716  20210720  51950    铜     SHFE
2   cu2108  20200818  20210816  20210817  20210819  50960    铜     SHFE
3   cu2109  20200916  20210915  20210916  20210922  52470    铜     SHFE
4   cu2110  20201016  20211015  20211018  20211020  51690    铜     SHFE
5   cu2111  20201117  20211115  20211116  20211118  53630    铜     SHFE
6   cu2112  20201216  20211215  20211216  20211220  57910    铜     SHFE
7   cu2201  20210118  20220117  20220118  20220120  59810    铜     SHFE
8   cu2202  20210208  20220215  20220216  20220218  58150    铜     SHFE
9   cu2203  20210316  20220315  20220316  20220318  67860    铜     SHFE
10  cu2204  20210416  20220415  20220418  20220420  67560    铜     SHFE
11  cu2205  20210518  20220516  20220517  20220519  75650    铜     SHFE

### 字符串的转义

In [392]:
df.name[0]

b'\\u94dc'

In [455]:
s = "高德路"
# 把字符串s编码成unicode
# 把字符串解码成utf-8,得到unicode的字符串
st = s.encode('unicode_escape').decode("utf8")
st

'\\u9ad8\\u5fb7\\u8def'

In [456]:
repr(st),repr(st).replace('\\\\', '\\')

("'\\\\u9ad8\\\\u5fb7\\\\u8def'", "'\\u9ad8\\u5fb7\\u8def'")

In [457]:
eval(repr(st).replace('\\\\', '\\'))

'高德路'

In [454]:
>>> a

b'O\\x8c\\x90\\x05\\xa1\\xe2!\\xbe'

>>> c = a.decode('unicode-escape').encode('ISO-8859-1')

>>> c

b'O\x8c\x90\x05\xa1\xe2!\xbe'

NameError: name 'a' is not defined

In [430]:
st.replace('\\u','\u')

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 0-1: truncated \uXXXX escape (<ipython-input-430-cc7a10a7422c>, line 1)

In [424]:
from pymysql.converters import escape_string
s = escape_string('\\u9ad8\\u5fb7\\u8def')
s.encode('raw_unicode_escape').decode("utf8")

'\\\\u9ad8\\\\u5fb7\\\\u8def'

In [ ]:
s = u'\xe6\x97\xa0\xe5\x90\x8d'
s.encode('raw_unicode_escape').decode("utf8")

In [396]:
import pymysql
import pandas as pd  
from sqlalchemy import create_engine 
yconnect = create_engine('mysql+pymysql://root:0000@localhost:3306/futures_c?charset=utf8mb4')  #
pd.io.sql.to_sql(df,'shfe_l', yconnect, schema='futures_c' , index = False, index_label=None,if_exists='replace')

DataError: (pymysql.err.DataError) (1366, "Incorrect string value: '\\xE9\\x93\\x9C' for column 'name' at row 1")
[SQL: INSERT INTO futures_c.shfe_l (`合约代码`, `上市日`, `到期日`, `开始交割日`, `最后交割日`, `挂牌基准价`, name, exchange) VALUES (%(合约代码)s, %(上市日)s, %(到期日)s, %(开始交割日)s, %(最后交割日)s, %(挂牌基准价)s, %(name)s, %(exchange)s)]
[parameters: ({'合约代码': 'cu2106', '上市日': 20200616, '到期日': 20210615, '开始交割日': 20210616, '最后交割日': 20210618, '挂牌基准价': 46520, 'name': '铜', 'exchange': 'SHFE'}, {'合约代码': 'cu2107', '上市日': 20200716, '到期日': 20210715, '开始交割日': 20210716, '最后交割日': 20210720, '挂牌基准价': 51950, 'name': '铜', 'exchange': 'SHFE'}, {'合约代码': 'cu2108', '上市日': 20200818, '到期日': 20210816, '开始交割日': 20210817, '最后交割日': 20210819, '挂牌基准价': 50960, 'name': '铜', 'exchange': 'SHFE'}, {'合约代码': 'cu2109', '上市日': 20200916, '到期日': 20210915, '开始交割日': 20210916, '最后交割日': 20210922, '挂牌基准价': 52470, 'name': '铜', 'exchange': 'SHFE'}, {'合约代码': 'cu2110', '上市日': 20201016, '到期日': 20211015, '开始交割日': 20211018, '最后交割日': 20211020, '挂牌基准价': 51690, 'name': '铜', 'exchange': 'SHFE'}, {'合约代码': 'cu2111', '上市日': 20201117, '到期日': 20211115, '开始交割日': 20211116, '最后交割日': 20211118, '挂牌基准价': 53630, 'name': '铜', 'exchange': 'SHFE'}, {'合约代码': 'cu2112', '上市日': 20201216, '到期日': 20211215, '开始交割日': 20211216, '最后交割日': 20211220, '挂牌基准价': 57910, 'name': '铜', 'exchange': 'SHFE'}, {'合约代码': 'cu2201', '上市日': 20210118, '到期日': 20220117, '开始交割日': 20220118, '最后交割日': 20220120, '挂牌基准价': 59810, 'name': '铜', 'exchange': 'SHFE'}  ... displaying 10 of 12 total bound parameter sets ...  {'合约代码': 'cu2204', '上市日': 20210416, '到期日': 20220415, '开始交割日': 20220418, '最后交割日': 20220420, '挂牌基准价': 67560, 'name': '铜', 'exchange': 'SHFE'}, {'合约代码': 'cu2205', '上市日': 20210518, '到期日': 20220516, '开始交割日': 20220517, '最后交割日': 20220519, '挂牌基准价': 75650, 'name': '铜', 'exchange': 'SHFE'})]
(Background on this error at: http://sqlalche.me/e/14/9h9h)

In [388]:
import pymysql
import pandas as pd
 
conn = pymysql.connect(host = "localhost",port=3306,user='root',passwd='0000',db='futures_c',charset="utf8")
sql_query = 'SELECT * FROM shfe_l'
df1 = pd.read_sql(sql_query, con=conn)
 
conn.close()  #使用完后记得关掉
df1

      合约代码       上市日       到期日     开始交割日     最后交割日  挂牌基准价    name exchange
0   cu2106  20200616  20210615  20210616  20210618  46520  \u94dc     SHFE
1   cu2107  20200716  20210715  20210716  20210720  51950  \u94dc     SHFE
2   cu2108  20200818  20210816  20210817  20210819  50960  \u94dc     SHFE
3   cu2109  20200916  20210915  20210916  20210922  52470  \u94dc     SHFE
4   cu2110  20201016  20211015  20211018  20211020  51690  \u94dc     SHFE
5   cu2111  20201117  20211115  20211116  20211118  53630  \u94dc     SHFE
6   cu2112  20201216  20211215  20211216  20211220  57910  \u94dc     SHFE
7   cu2201  20210118  20220117  20220118  20220120  59810  \u94dc     SHFE
8   cu2202  20210208  20220215  20220216  20220218  58150  \u94dc     SHFE
9   cu2203  20210316  20220315  20220316  20220318  67860  \u94dc     SHFE
10  cu2204  20210416  20220415  20220418  20220420  67560  \u94dc     SHFE
11  cu2205  20210518  20220516  20220517  20220519  75650  \u94dc     SHFE

In [389]:
df1.name = df1.name.str.decode(encoding='utf8')
df1

      合约代码       上市日       到期日     开始交割日     最后交割日  挂牌基准价  name exchange
0   cu2106  20200616  20210615  20210616  20210618  46520   NaN     SHFE
1   cu2107  20200716  20210715  20210716  20210720  51950   NaN     SHFE
2   cu2108  20200818  20210816  20210817  20210819  50960   NaN     SHFE
3   cu2109  20200916  20210915  20210916  20210922  52470   NaN     SHFE
4   cu2110  20201016  20211015  20211018  20211020  51690   NaN     SHFE
5   cu2111  20201117  20211115  20211116  20211118  53630   NaN     SHFE
6   cu2112  20201216  20211215  20211216  20211220  57910   NaN     SHFE
7   cu2201  20210118  20220117  20220118  20220120  59810   NaN     SHFE
8   cu2202  20210208  20220215  20220216  20220218  58150   NaN     SHFE
9   cu2203  20210316  20220315  20220316  20220318  67860   NaN     SHFE
10  cu2204  20210416  20220415  20220418  20220420  67560   NaN     SHFE
11  cu2205  20210518  20220516  20220517  20220519  75650   NaN     SHFE

In [230]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   合约代码      12 non-null     object
 1   上市日       12 non-null     int64
 2   到期日       12 non-null     int64
 3   开始交割日     12 non-null     int64
 4   最后交割日     12 non-null     int64
 5   挂牌基准价     12 non-null     int64
 6   exchange  12 non-null     object
dtypes: int64(5), object(2)
memory usage: 800.0+ bytes

In [208]:
df.columns

Index(['合约代码', '上市日', '到期日', '开始交割日', '最后交割日', '挂牌基准价', 'exchange', 'name'], dtype='object')

Python操作MySQL的步骤如下：

> 建立数据库连接  
> 通过 cursor() 创建游标对象（pymysql通过游标来执行sql和获取结果）  
> 使用 execute() 执行sql    
> 获取结果（查询）/提交事务（增删改）    
> 关闭游标    
> 关闭连接

* net start mysql 启动 mysql 服务    
* net stop mysql 关闭 mysql 服务   
* mysql -hlocalhost -uroot -proot 进入mysql数据库，其中-h表示服务器名，localhost表示本地；  -u为数据库用户名，root是mysql默认用户名；-p为密码，如果设置了密码，可直接在-p后直接输入。   
* 输入show databases；显示你有的数据库（mysql数据库中的命令必须以分号结尾“；”）；
* use databases名字；选择要操作的数据库；
* show tables; 显示所选数据库中的表；
* 如果要退出mysql数据库，输入exit;回车。
* 查看数据库数据存放的位置  show global variables like "%datadir%";

* CREATE DATABASE test_db;
* CREATE DATABASE IF NOT EXISTS test_db;
* drop database shfe;
* DROP TABLE table_name ;   
* SELECT concat('DROP TABLE IF EXISTS ', table_name, ';')  一次删除所有的表    
FROM information_schema.tables
WHERE table_schema = 'mydb';
SELECT concat('DROP TABLE IF EXISTS ', table_name, ';') FROM information_schema.tables WHERE table_schema = 'db_eastmoney';

### df数据写入数据库

In [253]:
import pymysql
import pandas as pd  
from sqlalchemy import create_engine

In [193]:
# import pymysql
# import pandas as pd
# from sqlalchemy import create_engine
# #建立连接，username替换为用户名，passwd替换为密码，test替换为数据库名
# conn = create_engine('mysql+pymysql://username:passwd@localhost:3306/test',encoding='utf8')  
# #写入数据，table_name为表名，‘replace’表示如果同名表存在就替换掉
# pd.io.sql.to_sql(df, "table_name", conn, if_exists='replace')

In [260]:
##将数据写入mysql的数据库，但需要先通过sqlalchemy.create_engine建立连接,且字符编码设置为utf8，否则有些latin字符不能处理  

# 第一个参数thedataframe是需要导入的pd dataframe,

# 第二个参数tablename是将导入的数据库中的表名

# 第三个参数yconnect是启动数据库的接口，pd 1.9以后的版本，除了sqllite，均需要通过sqlalchemy来设置

# 第四个参数databasename是将导入的数据库名字

# 第五个参数if_exists='append'的意思是，如果表tablename存在，则将数据添加到这个表的后面

yconnect = create_engine('mysql+pymysql://root:0000@localhost:3306/futures_c?charset=utf8mb4')  #
pd.io.sql.to_sql(df,'shfe_cu', yconnect, schema='futures_c' , index = False, index_label=None,if_exists='replace')
# df.to_sql('shfe_cu', yconnect,index = False, if_exists='replace')# index_label=None,

DataError: (pymysql.err.DataError) (1366, "Incorrect string value: '\\xE9\\x93\\x9C' for column 'name' at row 1")
[SQL: INSERT INTO futures_c.shfe_cu (`合约代码`, `上市日`, `到期日`, `开始交割日`, `最后交割日`, `挂牌基准价`, name) VALUES (%(合约代码)s, %(上市日)s, %(到期日)s, %(开始交割日)s, %(最后交割日)s, %(挂牌基准价)s, %(name)s)]
[parameters: ({'合约代码': 'cu2106', '上市日': 20200616, '到期日': 20210615, '开始交割日': 20210616, '最后交割日': 20210618, '挂牌基准价': 46520, 'name': '铜'}, {'合约代码': 'cu2107', '上市日': 20200716, '到期日': 20210715, '开始交割日': 20210716, '最后交割日': 20210720, '挂牌基准价': 51950, 'name': '铜'}, {'合约代码': 'cu2108', '上市日': 20200818, '到期日': 20210816, '开始交割日': 20210817, '最后交割日': 20210819, '挂牌基准价': 50960, 'name': '铜'}, {'合约代码': 'cu2109', '上市日': 20200916, '到期日': 20210915, '开始交割日': 20210916, '最后交割日': 20210922, '挂牌基准价': 52470, 'name': '铜'}, {'合约代码': 'cu2110', '上市日': 20201016, '到期日': 20211015, '开始交割日': 20211018, '最后交割日': 20211020, '挂牌基准价': 51690, 'name': '铜'}, {'合约代码': 'cu2111', '上市日': 20201117, '到期日': 20211115, '开始交割日': 20211116, '最后交割日': 20211118, '挂牌基准价': 53630, 'name': '铜'}, {'合约代码': 'cu2112', '上市日': 20201216, '到期日': 20211215, '开始交割日': 20211216, '最后交割日': 20211220, '挂牌基准价': 57910, 'name': '铜'}, {'合约代码': 'cu2201', '上市日': 20210118, '到期日': 20220117, '开始交割日': 20220118, '最后交割日': 20220120, '挂牌基准价': 59810, 'name': '铜'}  ... displaying 10 of 12 total bound parameter sets ...  {'合约代码': 'cu2204', '上市日': 20210416, '到期日': 20220415, '开始交割日': 20220418, '最后交割日': 20220420, '挂牌基准价': 67560, 'name': '铜'}, {'合约代码': 'cu2205', '上市日': 20210518, '到期日': 20220516, '开始交割日': 20220517, '最后交割日': 20220519, '挂牌基准价': 75650, 'name': '铜'})]
(Background on this error at: http://sqlalche.me/e/14/9h9h)

In [273]:
import pymysql

#打开数据库连接
conn = pymysql.connect(
        host='localhost',   # 本地服务器
        user='root',
        password='0000',  # 你的数据库密码
        port=3306,          # 默认端口
        charset = 'utf8',
        db = 'futures_c')
#创建游标对象
cursor = conn.cursor()

#sql预处理语句之创建表格
sql ="""CREATE TABLE IF NOT EXISTS shfe_l
    (code VARCHAR(30) NOT NULL,
     date1 VARCHAR(30) NOT NULL ,
     date2 VARCHAR (30) NOT NULL ,
     date3 VARCHAR (30) NOT NULL ,
     date4 VARCHAR (30) NOT NULL ,
     price INT(30) ,
     name VARCHAR (30) NOT NULL ,
     exchange VARCHAR (30) NOT NULL)"""

cursor.execute(sql)

#sql预处理语句之往表格中插入数据
sql = """ALTER TABLE shfe_l CONVERT TO CHARACTER SET utf8mb4"""

cursor.execute(sql)

#提交到数据库执行，代表一个事务的结束
conn.commit()

#关闭数据库
conn.close()

In [364]:

# df.to_sql('shfe_cu', yconnect,index = False, if_exists='replace')# index_label=None,

DataError: (pymysql.err.DataError) (1366, "Incorrect string value: '\\xE9\\x93\\x9C' for column 'name' at row 1")
[SQL: INSERT INTO futures_c.shfe_l (`合约代码`, `上市日`, `到期日`, `开始交割日`, `最后交割日`, `挂牌基准价`, name, exchange) VALUES (%(合约代码)s, %(上市日)s, %(到期日)s, %(开始交割日)s, %(最后交割日)s, %(挂牌基准价)s, %(name)s, %(exchange)s)]
[parameters: ({'合约代码': 'cu2106', '上市日': 20200616, '到期日': 20210615, '开始交割日': 20210616, '最后交割日': 20210618, '挂牌基准价': 46520, 'name': b'\xe9\x93\x9c', 'exchange': 'SHFE'}, {'合约代码': 'cu2107', '上市日': 20200716, '到期日': 20210715, '开始交割日': 20210716, '最后交割日': 20210720, '挂牌基准价': 51950, 'name': b'\xe9\x93\x9c', 'exchange': 'SHFE'}, {'合约代码': 'cu2108', '上市日': 20200818, '到期日': 20210816, '开始交割日': 20210817, '最后交割日': 20210819, '挂牌基准价': 50960, 'name': b'\xe9\x93\x9c', 'exchange': 'SHFE'}, {'合约代码': 'cu2109', '上市日': 20200916, '到期日': 20210915, '开始交割日': 20210916, '最后交割日': 20210922, '挂牌基准价': 52470, 'name': b'\xe9\x93\x9c', 'exchange': 'SHFE'}, {'合约代码': 'cu2110', '上市日': 20201016, '到期日': 20211015, '开始交割日': 20211018, '最后交割日': 20211020, '挂牌基准价': 51690, 'name': b'\xe9\x93\x9c', 'exchange': 'SHFE'}, {'合约代码': 'cu2111', '上市日': 20201117, '到期日': 20211115, '开始交割日': 20211116, '最后交割日': 20211118, '挂牌基准价': 53630, 'name': b'\xe9\x93\x9c', 'exchange': 'SHFE'}, {'合约代码': 'cu2112', '上市日': 20201216, '到期日': 20211215, '开始交割日': 20211216, '最后交割日': 20211220, '挂牌基准价': 57910, 'name': b'\xe9\x93\x9c', 'exchange': 'SHFE'}, {'合约代码': 'cu2201', '上市日': 20210118, '到期日': 20220117, '开始交割日': 20220118, '最后交割日': 20220120, '挂牌基准价': 59810, 'name': b'\xe9\x93\x9c', 'exchange': 'SHFE'}  ... displaying 10 of 12 total bound parameter sets ...  {'合约代码': 'cu2204', '上市日': 20210416, '到期日': 20220415, '开始交割日': 20220418, '最后交割日': 20220420, '挂牌基准价': 67560, 'name': b'\xe9\x93\x9c', 'exchange': 'SHFE'}, {'合约代码': 'cu2205', '上市日': 20210518, '到期日': 20220516, '开始交割日': 20220517, '最后交割日': 20220519, '挂牌基准价': 75650, 'name': b'\xe9\x93\x9c', 'exchange': 'SHFE'})]
(Background on this error at: http://sqlalche.me/e/14/9h9h)

In [254]:
import MySQLdb
db=MySQLdb.connect(host="localhost",port='3306',user="root",passwd="0000",db="futures_c")

df.to_sql(con=db, name='shfe_cu', if_exists='replace', flavor='mysql')

# conn = pymysql.connect(**config)
# pd.io.sql.to_sql(df,'shfe_cu', conn, schema='futures_c' , index = False, index_label=None,if_exists='replace')

ModuleNotFoundError: No module named 'MySQLdb'

### 在pandas中查询mysql中相关数据

In [223]:
import pymysql
import pandas as pd
 
conn = pymysql.connect(host = "localhost",port=3306,user='root',passwd='0000',db='futures_c',charset="utf8")
sql_query = 'SELECT * FROM shfe_cu'
df1 = pd.read_sql(sql_query, con=conn)
 
conn.close()  #使用完后记得关掉

In [224]:
df1

      合约代码       上市日       到期日     开始交割日     最后交割日  挂牌基准价 exchange
0   cu2106  20200616  20210615  20210616  20210618  46520     SHFE
1   cu2107  20200716  20210715  20210716  20210720  51950     SHFE
2   cu2108  20200818  20210816  20210817  20210819  50960     SHFE
3   cu2109  20200916  20210915  20210916  20210922  52470     SHFE
4   cu2110  20201016  20211015  20211018  20211020  51690     SHFE
5   cu2111  20201117  20211115  20211116  20211118  53630     SHFE
6   cu2112  20201216  20211215  20211216  20211220  57910     SHFE
7   cu2201  20210118  20220117  20220118  20220120  59810     SHFE
8   cu2202  20210208  20220215  20220216  20220218  58150     SHFE
9   cu2203  20210316  20220315  20220316  20220318  67860     SHFE
10  cu2204  20210416  20220415  20220418  20220420  67560     SHFE
11  cu2205  20210518  20220516  20220517  20220519  75650     SHFE

In [225]:
df1.columns

Index(['合约代码', '上市日', '到期日', '开始交割日', '最后交割日', '挂牌基准价', 'exchange'], dtype='object')

In [ ]:
ALTER TABLE shfe_cu CONVERT TO CHARACTER SET utf8mb4;

In [391]:
s = '\xE9\x93\x9C'
s.encode('raw_unicode_escape').decode("utf8")

'铜'

In [342]:
s = u'\xe6\x97\xa0\xe5\x90\x8d'
s.encode('raw_unicode_escape').decode("utf8")

'无名'

In [305]:
from pymysql.converters import escape_string
s = u'\\xE9\\x93\\x9C'
s = s.encode('raw_unicode_escape')
# s.decode('utf-8')
# s.replace('\\\\','\\')
s.decode()

'\\xE9\\x93\\x9C'

In [306]:
'中文'.decode('utf8')

AttributeError: 'str' object has no attribute 'decode'